name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**'  ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install plugin
      run: |
        mkdir tmp
        cd tmp
        Invoke-WebRequest -Uri "https://nsis.sourceforge.io/mediawiki/images/4/4a/AccessControl.zip" -OutFile AccessControl.zip
        Expand-Archive -LiteralPath .\AccessControl.zip -DestinationPath "C:\Program Files (x86)\NSIS\Plugins\x86-unicode\" -Force
    - name: Run build
        make
